### ISSUE TITLE
TODO-20230801

### ISSUE THREAD

**Issue by Jinjin89** [Jinjin89/bioClass#1]
- [ ] write data into hdf5 format
- [ ] load the data into hdf5
- [ ] subet/filter
- [ ] show method in detail mode

# assay_expr

- [ ] add cpm function, transform count data into cpm
- [ ] extract_data
